=== xBimTeam/XbimEssentials/Xbim.IO/Xml/BsConf/cnf.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- Mit XMLSpy v2009 (http://www.altova.com) von Thomas Liebich (AEC3 Deutschland GmbH) bearbeitet -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:cnf="urn:iso:std:iso:10303:-28:ed-2:tech:XMLschema:configuration_language" 
targetNamespace="urn:iso:std:iso:10303:-28:ed-2:tech:XMLschema:configuration_language" elementFormDefault="unqualified" attributeFormDefault="unqualified">
	<xs:element name="configuration" nillable="true">
		<xs:complexType>
			<xs:choice minOccurs="0" maxOccurs="unbounded">
				<xs:element name="include">
					<xs:complexType>
						<xs:attribute name="configuration" type="xs:IDREF" use="required"/>
					</xs:complexType>
				</xs:element>
				<xs:element ref="cnf:option"/>
				<xs:element ref="cnf:type"/>
				<xs:element ref="cnf:entity"/>
				<xs:element ref="cnf:schema"/>
				<xs:element ref="cnf:uosElement"/>
				<xs:element ref="cnf:uosEntity"/>
				<xs:element ref="cnf:rootEntity"/>
			</xs:choice>
			<xs:attribute name="id" type="xs:ID" use="required"/>
			<xs:attribute name="targetNamespace" type="xs:anyURI" use="optional"/>
			<xs:attribute name="schema" type="xs:IDREF" use="optional"/>
			<xs:attribute name="configuration-location" type="cnf:Seq-anyURI" use="optional"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="option">
		<xs:complexType>
			<xs:attribute name="inheritance" type="xs:boolean" default="false"/>
			<xs:attribute name="exp-type" type="cnf:exp-type" default="unspecified"/>
			<xs:attribute name="entity-attribute" type="cnf:exp-attribute-global" default="double-tag"/>
			<xs:attribute name="concrete-attribute" type="cnf:exp-attribute-global" default="attribute-tag"/>
			<xs:attribute name="tagless" type="cnf:boolean_or_unspecified" default="unspecified"/>
			<xs:attribute name="naming-convention" type="cnf:naming-convention" default="initial-upper"/>
			<xs:attribute name="keep-all" type="cnf:attributeType"/>
			<xs:attribute name="generate-keys" type="xs:boolean" default="true"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="type">
		<xs:complexType>
			<xs:choice minOccurs="0">
				<xs:element ref="cnf:aggregate"/>
			</xs:choice>
			<xs:attribute name="select" type="cnf:patterns" use="required"/>
			<xs:attribute name="name" type="xs:NMTOKEN" use="optional"/>
			<xs:attribute name="map" type="xs:NMTOKEN" use="optional"/>
			<xs:attribute name="exp-type" type="cnf:exp-type" use="optional"/>
			<xs:attribute name="tagless" type="cnf:boolean_or_unspecified" use="optional"/>
			<xs:attribute name="notation" type="xs:normalizedString" use="optional"/>
			<xs:attribute name="keep" type="xs:boolean" default="true"/>
			<xs:attribute name="flatten" type="xs:boolean" use="optional"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="entity">
		<xs:complexType>
			<xs:choice minOccurs="0" maxOccurs="unbounded">
				<xs:element ref="cnf:attribute"/>
				<xs:element ref="cnf:inverse"/>
			</xs:choice>
			<xs:attribute name="select" type="cnf:patterns" use="optional"/>
			<xs:attribute name="synthetic" use="optional">
				<xs:simpleType>
					<xs:restriction>
						<xs:simpleType>
							<xs:list itemType="xs:Name"/>
						</xs:simpleType>
						<xs:minLength value="2"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
			<xs:attribute name="inheritance" type="xs:boolean" default="false"/>
			<xs:attribute name="name" type="xs:NMTOKEN" use="optional"/>
			<xs:attribute name="tag-source" type="xs:NMTOKEN" use="optional"/>
			<xs:attribute name="tag-values" type="xs:NMTOKENS" use="optional"/>
			<xs:attribute name="map" type="xs:NMTOKEN" use="optional"/>
			<xs:attribute name="exp-type" type="cnf:exp-type" use="optional"/>
			<xs:attribute name="content" type="cnf:content" use="optional"/>
			<xs:attribute name="exp-attribute" type="cnf:exp-attribute" default="unspecified"/>
			<xs:attribute name="tagless" type="cnf:boolean_or_unspecified" use="optional"/>
			<xs:attribute name="keep" type="xs:boolean" default="true"/>
			<xs:attribute name="new" type="xs:boolean" default="false"/>
			<xs:attribute name="implementation" type="xs:string" use="optional"/>
			<xs:attribute name="facet" type="xs:string" use="optional"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="attribute">
		<xs:complexType>
			<xs:choice minOccurs="0" maxOccurs="unbounded">
				<xs:element ref="cnf:aggregate"/>
			</xs:choice>
			<xs:attribute name="select" type="xs:NMTOKEN" use="optional"/>
			<xs:attribute name="new" type="xs:boolean" default="false"/>
			<xs:attribute name="name" type="xs:NMTOKEN" use="optional"/>
			<xs:attribute name="exp-attribute" type="cnf:exp-attribute" use="optional"/>
			<xs:attribute name="content" type="cnf:content" use="optional"/>
			<xs:attribute name="aggregate-content" type="cnf:content" use="optional"/>
			<xs:attribute name="map" type="xs:NMTOKEN" use="optional"/>
			<xs:attribute name="use-id" type="xs:boolean" use="optional"/>
			<xs:attribute name="keep" type="xs:boolean" default="true"/>
			<xs:attribute name="tagless" type="cnf:boolean_or_unspecified" use="optional"/>
			<xs:attribute name="notation" type="xs:normalizedString" use="optional"/>
			<xs:attribute name="flatten" type="xs:boolean" use="optional"/>
			<xs:attribute name="ref" type="xs:NMTOKEN" use="optional"/>
			<xs:attribute name="use" type="xs:NMTOKEN" use="optional"/>
			<xs:attribute name="implementation" type="xs:string" use="optional"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="inverse">
		<xs:complexType>
			<xs:attribute name="select" type="xs:NMTOKEN" use="optional"/>
			<xs:attribute name="name" type="xs:NMTOKEN" use="optional"/>
			<xs:attribute name="exp-attribute" type="cnf:exp-attribute" use="optional"/>
			<xs:attribute name="content" type="cnf:content" use="optional"/>
			<xs:attribute name="tagless" type="cnf:boolean_or_unspecified" use="optional"/>
			<xs:attribute name="invert" type="xs:NMTOKEN" use="optional"/>
			<xs:attribute name="map" type="xs:NMTOKEN" use="optional"/>
			<xs:attribute name="keep" type="xs:boolean" default="false"/>
			<xs:attribute name="minOccurs" type="xs:nonNegativeInteger" use="optional" default="0"/>
			<xs:attribute name="maxOccurs" type="cnf:nonNegativeInteger_or_unbounded" use="optional" default="unbounded"/>
			<xs:attribute name="ref" type="xs:NMTOKEN" use="optional"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="aggregate">
		<xs:complexType>
			<xs:choice minOccurs="0" maxOccurs="unbounded">
				<xs:element ref="cnf:aggregate"/>
			</xs:choice>
			<xs:attribute name="name" type="xs:NMTOKEN" use="optional"/>
			<xs:attribute name="content" type="cnf:content" use="optional"/>
			<xs:attribute name="tagless" type="cnf:boolean_or_unspecified" use="optional"/>
			<xs:attribute name="use-id" type="xs:boolean" use="optional"/>
			<xs:attribute name="flatten" type="xs:boolean" use="optional"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="schema">
		<xs:complexType>
			<xs:choice maxOccurs="unbounded">
				<xs:element ref="cnf:namespace" minOccurs="0" maxOccurs="unbounded"/>
				<xs:element ref="cnf:include" minOccurs="0" maxOccurs="unbounded"/>
				<xs:element ref="cnf:containerObject" minOccurs="0"/>
				<xs:element ref="cnf:additionalObject" minOccurs="0" maxOccurs="unbounded"/>
			</xs:choice>
			<xs:attribute name="targetNamespace" type="xs:anyURI"/>
			<xs:attribute name="elementFormDefault" type="cnf:qual"/>
			<xs:attribute name="attributeFormDefault" type="cnf:qual"/>
			<xs:attribute name="defaultRootObjectType" type="xs:string"/>
			<xs:attribute name="defaultObjectType" type="xs:string"/>
			<xs:attribute name="schema-version" type="xs:string"/>
			<xs:attribute name="embed-schema-items" type="xs:boolean" default="false"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="containerObject">
		<xs:complexType>
			<xs:attribute name="name" type="xs:NMTOKEN" use="required"/>
			<xs:attribute name="implementation" type="xs:string" use="optional"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="additionalObject">
		<xs:complexType>
			<xs:attribute name="name" type="xs:NMTOKEN" use="required"/>
			<xs:attribute name="implementation" type="xs:string" use="optional"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="namespace">
		<xs:complexType>
			<xs:attribute name="alias" type="xs:anyURI"/>
			<xs:attribute name="prefix" type="xs:string"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="include">
		<xs:complexType>
			<xs:attribute name="urn" type="xs:anyURI"/>
			<xs:attribute name="schema-location" type="xs:string"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="addAttribute">
		<xs:complexType>
			<xs:attribute name="name" type="xs:QName" use="required"/>
			<xs:attribute name="ref" type="xs:boolean" default="false"/>
			<xs:attribute name="type" type="xs:QName" use="optional"/>
			<xs:attribute name="usage" default="optional">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:enumeration value="optional"/>
						<xs:enumeration value="required"/>
						<xs:enumeration value="fixed"/>
						<xs:enumeration value="default"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
			<xs:attribute name="value" type="xs:string" use="optional"/>
		</xs:complexType>
	</xs:element>
	<xs:simpleType name="exp-type">
		<xs:restriction base="xs:string">
      <xs:enumeration value="unspecified"/>
      <xs:enumeration value="root"/>
      <xs:enumeration value="value"/>
    </xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="exp-attribute">
		<xs:restriction base="xs:string">
      <xs:enumeration value="unspecified"/>
      <xs:enumeration value="double-tag"/>
			<xs:enumeration value="attribute-tag"/>
			<xs:enumeration value="type-tag"/>
			<xs:enumeration value="no-tag"/>
			<xs:enumeration value="no-tag-simple"/>
			<xs:enumeration value="attribute-content"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="exp-attribute-global">
		<xs:restriction base="xs:string">
			<xs:enumeration value="double-tag"/>
			<xs:enumeration value="attribute-tag"/>
			<xs:enumeration value="attribute-content"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="content">
		<xs:restriction base="xs:string">
      <xs:enumeration value="unspecified"/>
      <xs:enumeration value="value"/>
			<xs:enumeration value="ref"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="naming-convention">
		<xs:restriction base="xs:string">
			<xs:enumeration value="initial-upper"/>
			<xs:enumeration value="camel-case"/>
			<xs:enumeration value="preserve-case"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="boolean_or_unspecified">
		<xs:union memberTypes="xs:boolean">
			<xs:simpleType>
				<xs:restriction base="xs:string">
					<xs:enumeration value="unspecified"/>
				</xs:restriction>
			</xs:simpleType>
		</xs:union>
	</xs:simpleType>
	<xs:simpleType name="attributeType">
		<xs:restriction base="xs:normalizedString">
			<xs:enumeration value="inverse"/>
			<xs:enumeration value="derive"/>
			<xs:enumeration value="derive-inverse"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="nonNegativeInteger_or_unbounded">
		<xs:union memberTypes="xs:nonNegativeInteger">
			<xs:simpleType>
				<xs:restriction base="xs:string">
					<xs:enumeration value="unbounded"/>
				</xs:restriction>
			</xs:simpleType>
		</xs:union>
	</xs:simpleType>
	<xs:simpleType name="patterns">
		<xs:restriction>
			<xs:simpleType>
				<xs:list itemType="xs:normalizedString"/>
			</xs:simpleType>
			<xs:minLength value="1"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="qual">
		<xs:restriction base="xs:string">
			<xs:enumeration value="qualified"/>
			<xs:enumeration value="unqualified"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="Seq-anyURI">
		<xs:list itemType="xs:anyURI"/>
	</xs:simpleType>
	<xs:element name="uosElement">
		<xs:complexType>
			<xs:choice minOccurs="0">
				<xs:element ref="cnf:addAttribute"/>
			</xs:choice>
			<xs:attribute name="name" type="xs:NMTOKEN" use="required"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="uosEntity">
		<xs:complexType>
			<xs:choice minOccurs="0">
				<xs:element ref="cnf:addAttribute"/>
			</xs:choice>
			<xs:attribute name="name" type="xs:NMTOKEN" use="required"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="rootEntity">
		<xs:complexType>
			<xs:choice minOccurs="0">
				<xs:element ref="cnf:addAttribute"/>
			</xs:choice>
			<xs:attribute name="name" type="xs:NMTOKEN" use="required"/>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== xBimTeam/XbimEssentials/Xbim.IO.MemoryModel/Xml/BsConf/IFC4_ADD1_config.xml
<?xml version="1.0" encoding="utf-8"?>
<cnf:configuration xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" id="IFC4" xsi:schemaLocation="urn:iso:std:iso:10303:-28:ed-2:tech:XMLschema:configuration_language http://www.buildingsmart-tech.org/ifcXML/IFC4/P28/cnf.xsd" xmlns:cnf="urn:iso:std:iso:10303:-28:ed-2:tech:XMLschema:configuration_language">
  <cnf:option 
    inheritance="true" 
    concrete-attribute="attribute-content" 
    naming-convention="preserve-case" 
    generate-keys="false" />
  <cnf:schema targetNamespace="http://www.buildingsmart-tech.org/ifcXML/IFC4/final" elementFormDefault="qualified" attributeFormDefault="unqualified" embed-schema-items="true">
    <cnf:namespace prefix="ifc" alias="http://www.buildingsmart-tech.org/ifcXML/IFC4/final" />
  </cnf:schema>
  <cnf:uosElement name="ifcXML" />
  <cnf:type select="NUMBER" map="xs:double" />
  <cnf:type select="BINARY" map="xs:hexBinary" />
  <cnf:type select="IfcStrippedOptional" keep="false" />
  <cnf:entity select="IfcAnnotationFillArea">
    <cnf:attribute select="OuterBoundary" exp-attribute="attribute-tag" />
  </cnf:entity>
  <cnf:entity select="IfcApplication">
    <cnf:attribute select="ApplicationDeveloper" exp-attribute="attribute-tag" />
  </cnf:entity>
  <cnf:entity select="IfcAppliedValue">
    <cnf:attribute select="UnitBasis" exp-attribute="attribute-tag" />
  </cnf:entity>
  <cnf:entity select="IfcApprovalRelationship">
    <cnf:attribute select="RelatingApproval" exp-attribute="attribute-tag" />
  </cnf:entity>
  <cnf:entity select="IfcArbitraryClosedProfileDef">
    <cnf:attribute select="OuterCurve" exp-attribute="attribute-tag" />
  </cnf:entity>
  <cnf:entity select="IfcArbitraryOpenProfileDef">
    <cnf:attribute select="Curve" exp-attribute="attribute-tag" />
  </cnf:entity>
  <cnf:entity select="IfcAsset">
    <cnf:attribute select="OriginalValue" exp-attribute="attribute-tag" />
    <cnf:attribute select="CurrentValue" exp-attribute="attribute-tag" />
    <cnf:attribute select="TotalReplacementCost" exp-attribute="attribute-tag" />
    <cnf:attribute select="ResponsiblePerson" exp-attribute="attribute-tag" />
    <cnf:attribute select="DepreciatedValue" exp-attribute="attribute-tag" />
  </cnf:entity>
  <cnf:entity select="IfcAxis1Placement">
    <cnf:attribute select="Axis" exp-attribute="attribute-tag" />
  </cnf:entity>
  <cnf:entity select="IfcAxis2Placement2D">
    <cnf:attribute select="RefDirection" exp-attribute="attribute-tag" />
  </cnf:entity>
  <cnf:entity select="IfcAxis2Placement3D">
    <cnf:attribute select="Axis" exp-attribute="attribute-tag" />
    <cnf:attribute select="RefDirection" exp-attribute="attribute-tag" />
  </cnf:entity>
  <cnf:entity select="IfcBlobTexture">
    <cnf:attribute select="RasterCode" exp-attribute="attribute-tag" />
  </cnf:entity>
  <cnf:entity select="IfcBoundingBox">
    <cnf:attribute select="Corner" exp-attribute="attribute-tag" />
  </cnf:entity>
  <cnf:entity select="IfcBoxedHalfSpace">
    <cnf:attribute select="Enclosure" exp-attribute="attribute-tag" />
  </cnf:entity>
  <cnf:entity select="IfcBSplineSurface">
    <cnf:attribute select="ControlPointsList" exp-attribute="double-tag" />
  </cnf:entity>
  <cnf:entity select="IfcBuilding">
    <cnf:attribute select="BuildingAddress" exp-attribute="attribute-tag" />
  </cnf:entity>
  <cnf:entity select="IfcCartesianPointList3D">
    <cnf:attribute select="CoordList" exp-attribute="attribute-content" tagless="true" />
  </cnf:entity>
  <cnf:entity select="IfcCartesianTransformationOperator">
    <cnf:attribute select="Axis1" exp-attribute="attribute-tag" />
    <cnf:attribute select="Axis2" exp-attribute="attribute-tag" />
    <cnf:attribute select="LocalOrigin" exp-attribute="attribute-tag" />
  </cnf:entity>
  <cnf:entity select="IfcCartesianTransformationOperator3D">
    <cnf:attribute select="Axis3" exp-attribute="attribute-tag" />
  </cnf:entity>
  <cnf:entity select="IfcClassification">
    <cnf:attribute select="ReferenceTokens" exp-attribute="double-tag" />
    <cnf:inverse select="HasReferences" exp-attribute="double-tag" />
  </cnf:entity>
  <cnf:entity select="IfcClassificationReference">
    <cnf:attribute select="ReferencedSource" keep="false" />
    <cnf:inverse select="HasReferences" exp-attribute="double-tag" />
  </cnf:entity>
  <cnf:entity select="IfcColourRgbList">
    <cnf:attribute select="ColourList" exp-attribute="attribute-content" tagless="true" />
  </cnf:entity>
  <cnf:entity select="IfcCompositeCurveSegment">
    <cnf:attribute select="ParentCurve" exp-attribute="attribute-tag" />
  </cnf:entity>
  <cnf:entity select="IfcConstructionResource">
    <cnf:attribute select="Usage" exp-attribute="attribute-tag" />
    <cnf:attribute select="BaseQuantity" exp-attribute="attribute-tag" />
  </cnf:entity>
  <cnf:entity select="IfcConstructionResourceType">
    <cnf:attribute select="BaseQuantity" exp-attribute="attribute-tag" />
  </cnf:entity>
  <cnf:entity select="IfcContext">
    <cnf:attribute select="UnitsInContext" exp-attribute="attribute-tag" />
    <cnf:inverse select="IsDefinedBy" exp-attribute="double-tag" />
    <cnf:inverse select="Declares" exp-attribute="double-tag" />
  </cnf:entity>
  <cnf:entity select="IfcConversionBasedUnit">
    <cnf:attribute select="ConversionFactor" exp-attribute="attribute-tag" />
  </cnf:entity>
  <cnf:entity select="IfcCoordinateOperation">
    <cnf:attribute select="SourceCRS" keep="false" />
    <cnf:attribute select="TargetCRS" exp-attribute="attribute-tag" />
  </cnf:entity>
  <cnf:entity select="IfcCsgPrimitive3D">
    <cnf:attribute select="Position" exp-attribute="attribute-tag" />
  </cnf:entity>
  <cnf:entity select="IfcCurrencyRelationship">
    <cnf:attribute select="RelatingMonetaryUnit" exp-attribute="attribute-tag" />
    <cnf:attribute select="RelatedMonetaryUnit" exp-attribute="attribute-tag" />
    <cnf:attribute select="RateSource" exp-attribute="attribute-tag" />
  </cnf:entity>
  <cnf:entity select="IfcCurveBoundedPlane">
    <cnf:attribute select="BasisSurface" exp-attribute="attribute-tag" />
    <cnf:attribute select="OuterBoundary" exp-attribute="attribute-tag" />
  </cnf:entity>
  <cnf:entity select="IfcCurveBoundedSurface">
    <cnf:attribute select="BasisSurface" exp-attribute="attribute-tag" />
  </cnf:entity>
  <cnf:entity select="IfcDerivedProfileDef">
    <cnf:attribute select="ParentProfile" exp-attribute="attribute-tag" />
    <cnf:attribute select="Operator" exp-attribute="attribute-tag" />
  </cnf:entity>
  <cnf:entity select="IfcDerivedUnitElement">
    <cnf:attribute select="Unit" exp-attribute="attribute-tag" />
  </cnf:entity>
  <cnf:entity select="IfcDocumentInformationRelationship">
    <cnf:attribute select="RelatingDocument" exp-attribute="attribute-tag" />
  </cnf:entity>
  <cnf:entity select="IfcDocumentReference">
    <cnf:attribute select="ReferencedDocument" exp-attribute="attribute-tag" />
  </cnf:entity>
  <cnf:entity select="IfcDoorLiningProperties">
    <cnf:attribute select="ShapeAspectStyle" exp-attribute="attribute-tag" />
  </cnf:entity>
  <cnf:entity select="IfcDoorPanelProperties">
    <cnf:attribute select="ShapeAspectStyle" exp-attribute="attribute-tag" />
  </cnf:entity>
  <cnf:entity select="IfcEdge">
    <cnf:attribute select="EdgeStart" exp-attribute="attribute-tag" />
    <cnf:attribute select="EdgeEnd" exp-attribute="attribute-tag" />
  </cnf:entity>
  <cnf:entity select="IfcEdgeCurve">
    <cnf:attribute select="EdgeGeometry" exp-attribute="attribute-tag" />
  </cnf:entity>
  <cnf:entity select="IfcElementarySurface">
    <cnf:attribute select="Position" exp-attribute="attribute-tag" />
  </cnf:entity>
  <cnf:entity select="IfcEvent">
    <cnf:attribute select="EventOccurenceTime" exp-attribute="attribute-tag" />
  </cnf:entity>
  <cnf:entity select="IfcExternalReferenceRelationship">
    <cnf:attribute select="RelatingReference" exp-attribute="attribute-tag" />
  </cnf:entity>
  <cnf:entity select="IfcExtrudedAreaSolid">
    <cnf:attribute select="ExtrudedDirection" exp-attribute="attribute-tag" />
  </cnf:entity>
  <cnf:entity select="IfcExtrudedAreaSolidTapered">
    <cnf:attribute select="EndSweptArea" exp-attribute="attribute-tag" />
  </cnf:entity>
  <cnf:entity select="IfcFaceBound">
    <cnf:attribute select="Bound" exp-attribute="attribute-tag" />
  </cnf:entity>
  <cnf:entity select="IfcFaceSurface">
    <cnf:attribute select="FaceSurface" exp-attribute="attribute-tag" />
  </cnf:entity>
  <cnf:entity select="IfcFillAreaStyleHatching">
    <cnf:attribute select="HatchLineAppearance" exp-attribute="attribute-tag" />
    <cnf:attribute select="PointOfReferenceHatchLine" exp-attribute="attribute-tag" />
    <cnf:attribute select="PatternStart" exp-attribute="attribute-tag" />
  </cnf:entity>
  <cnf:entity select="IfcFixedReferenceSweptAreaSolid">
    <cnf:attribute select="Directrix" exp-attribute="attribute-tag" />
    <cnf:attribute select="FixedReference" exp-attribute="attribute-tag" />
  </cnf:entity>
  <cnf:entity select="IfcGeometricRepresentationContext">
    <cnf:attribute select="WorldCoordinateSystem" exp-attribute="double-tag" />
    <cnf:attribute select="TrueNorth" exp-attribute="attribute-tag" />
    <cnf:inverse select="HasSubContexts" exp-attribute="double-tag" />
    <cnf:inverse select="HasCoordinateOperation" exp-attribute="attribute-tag" />
  </cnf:entity>
  <cnf:entity select="IfcGeometricRepresentationSubContext">
    <cnf:attribute select="ParentContext" keep="false" />
  </cnf:entity>
  <cnf:entity select="IfcGridAxis">
    <cnf:attribute select="AxisCurve" exp-attribute="attribute-tag" />
  </cnf:entity>
  <cnf:entity select="IfcGridPlacement">
    <cnf:attribute select="PlacementLocation" exp-attribute="attribute-tag" />
  </cnf:entity>
  <cnf:entity select="IfcHalfSpaceSolid">
    <cnf:attribute select="BaseSurface" exp-attribute="attribute-tag" />
  </cnf:entity>
  <cnf:entity select="IfcIndexedColourMap">
